config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', to: 'users#dashboard'
  get 'my-virds', to: 'users#virds'

  devise_for :users
  root to: 'pages#home'

  resources :vacuums do
    resources :bookings
  end
end

app/models/vacuum.rb
class Vacuum < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  MODELS = %w(rx-9000 rx-7000 rx-8500 eagle annihilator decko\ 2000x)

  VACCUM_PHOTOS = {
    "rx-9000" => "https://res.cloudinary.com/druzius/image/upload/v1542696605/r2d2.png",
    "rx-7000" => "https://res.cloudinary.com/druzius/image/upload/v1542696601/henry.jpg",
    "rx-8500" => "https://res.cloudinary.com/druzius/image/upload/v1542696601/hetty.jpg",
    "eagle" => "https://res.cloudinary.com/druzius/image/upload/v1542696602/rosie-robot.jpg",
    "annihilator" => "https://res.cloudinary.com/druzius/image/upload/v1542698264/default_vird.jpg",
    "decko 2000x" => "https://res.cloudinary.com/druzius/image/upload/v1542696601/wall-e.jpg"
  }

  before_validation :set_image

  belongs_to :user
  has_many :bookings, dependent: :destroy
  # has_many :users, through: :bookings

  validates :model, inclusion: { in: MODELS }
  validates :price, presence: true
  validates :address, presence: true

  # include PgSearch
  # pg_search_scope :search_by_model_and_address,
  #   against: [ :model, :address ],
  #   using: {
  #     tsearch: { prefix: true }
  #   }

  include PgSearch
  pg_search_scope :global_search,
    against: [ :model, :address ],
    associated_against: {
      user: [:first_name, :last_name]
    },
    using: {
      tsearch: { prefix: true }
    }

  private

  def set_image
    self.image = VACCUM_PHOTOS[model]
  end
end

app/controllers/vacuums_controller.rb
class VacuumsController < ApplicationController
  before_action :set_vacuum, only: [:show, :destroy, :edit]

  # ayout 'map', only: :index

  def index
    @vacuums = Vacuum.where.not(latitude: nil, longitude: nil)
    @query = params.dig(:search, :query)
    @vacuums = @vacuums.global_search(@query) if @query.present?

    # Array - Active Record queries need to come above
    @vacuums = @vacuums - current_user.owned_vacuums if current_user

    @markers = @vacuums.map do |vacuum|
      {
        lng: vacuum.longitude,
        lat: vacuum.latitude,
        infoWindow: { content: render_to_string(partial: "vacuums/vacuum_window", locals: { vacuum: vacuum }) }
      }
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @vacuum = Vacuum.new
  end

  def create
    @vacuum = Vacuum.new(vacuum_params)
    @vacuum.user = current_user

    if @vacuum.save
      redirect_to my_virds_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @vacuum = Vacuum.find(params[:id])
    @vacuum.update(vacuum_params)
    redirect_to root_path
  end

  def destroy
    @vacuum = Vacuum.find(params[:id])
    @vacuum.destroy
    redirect_to request.referer
  end

  private

  def vacuum_params
    params.require(:vacuum).permit(:model, :price, :address, :available)
  end

  def set_vacuum
    @vacuum = Vacuum.find(params[:id])
  end
end

app/views/vacuums/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">

      <div class="form-login">

        <h2>My Vird</h2>
        <%= simple_form_for(@vacuum) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="form-inputs">
            <%= f.input :model, collection: Vacuum::MODELS, label: "Model" , include_blank: false %>
          </div>

          <div class="form-inputs">
            <%= f.input :price %>
          </div>

          <div class="form-inputs">
            <%= f.input :address %>
          </div>

          <div class="form-inputs">
            <%= f.input :available %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, class: "btn btn-warning" %>
          </div>
        <% end %>
          <%= link_to 'Back', vacuums_path %>
      </div>

    </div>
  </div>
</div>

app/views/vacuums/_vacuum.html.erb
<div class="col-xs-12 col-sm-6 col-md-4">
   <div class="vacuum">

    <div class="vacuum-image" style="background: linear-gradient(to bottom,rgba(20,20,20, 0.2),rgba(76,76,76,0.2) 30%), url(<%= image_path(vacuum.image) %>) center / contain no-repeat;"></div>
      <div class="vacuum-content">
        <div class="vacuum-info">
          <div class="vacuum-name">
            <%= vacuum.model %>
          </div>

          <div class="vacuum-available">
            <% if vacuum.available? %>
              <div class="available">Available</div>
            <% else %>
              <div class="unavailable">Unavailable</div>
            <% end %>
          </div>

          <div class="vacuum-price">
            <p>$<%= vacuum.price %>/hour</p>
          </div>
        </div>
        <div class="vacuum-owner">
          <p>By <%= vacuum.user.first_name %></p>
        </div>
      <div class="vacuum-booking">
        <%= link_to "View Details", vacuum_path(vacuum), class: "btn-sm btn-warning centered-button" %>
      </div>
    </div>
  </div>
</div>

app/views/vacuums/_vacuum_window.html.erb
Model:
<%= vacuum.model %> |
<%= vacuum.address %>

app/views/vacuums/edit.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <%= render 'form', vacuum: @vacuum %>


</div>

app/views/vacuums/index.html.erb
<div class="map-wrapper">
  <div id="vacuums">

 <div class="form-wrapper">
  <%= simple_form_for :search, url: vacuums_path, method: :get do |f| %>
  <div id="search-bar">
    <%= f.input :query, label: false, placeholder: "Find a Vird" %>
  </div>
  <% end %>
  <% if @query %>
  <div id="show-btn">
    <%= link_to "Show All", vacuums_path, class: "btn btn-warning btn-sm" %>
  </div>
  <% end %>
</div>

<% if @vacuums.empty? %>
<h2>No results found.</h2>
<% else %>
<div class="index-title">
  <h2>Top Virds</h2>
</div>
<div class="row">
  <%= render @vacuums %>
</div>
<% end %>

</div>

<div
id="map"
data-markers="<%= @markers.to_json %>"
data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>
</div>

app/views/vacuums/new.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <%= render 'form', vacuum: @vacuum %>



</div>

app/views/vacuums/show.html.erb
<p id="notice"><%= notice %></p>

<div class="info-dash">
  <div class="main">
    <%= image_tag(@vacuum.image, class: 'vacuum-img') %>
    <strong><%= @vacuum.model.capitalize %></strong><br>
    <p>$<%= @vacuum.price %>/hour</p>
    <p><%= @vacuum.address %></p>
    <% if @vacuum.available %>
    <p style="color:green"><strong>Available</strong><br></p>
    <%= link_to 'Book', new_vacuum_booking_path(@vacuum), class: "btn btn-warning" %>
    <% else %>
    <p style="color: red"> Unavailable</p>
    <% end %>
  </div>
  <div class="stat">
    <div class="stat-content"><h3><%= rand(3..14) %></h3><br>Watchers</div>
  </div>
  <div class="stat">
    <div class="stat-content"><h3><%= rand(30..100) %></h3><br>Orders</div>
  </div>
  <div class="stat">
    <div class="stat-content"><h3><%= rand(10..20) %></h3><br>Reviews</div>
  </div>
  <div class="description">
    <div class="description-content">
      <h3>Vird info</h3>
      <p class="text-justify">
        The <%= @vacuum.model  %> cleaner, also known as a <strong>Vird</strong>, is a device that uses an air pump (a centrifugal fan in all but some of the very oldest models), to create a partial vacuum to suck up dust and dirt, usually from floors, and from other surfaces such as upholstery and draperies. Contact <%= @vacuum.user.first_name  %> by email for further information about his/her <strong>Vird</strong>. <br> Contact detail - <%= @vacuum.user.email  %>
      </p>
    </div>
  </div>
  <%= link_to vacuums_path do %>
    <i class="fa fa-chevron-circle-left" style="font-size:24px; color: black"></i>
  <% end %>
</div>