config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', to: 'users#dashboard'
  get 'my-virds', to: 'users#virds'

  devise_for :users
  root to: 'pages#home'

  resources :vacuums do
    resources :bookings
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_many :booked_vacuums, through: :bookings, source: :vacuum
  has_many :owned_vacuums, class_name: 'Vacuum'
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
 # before_action :configure_sign_up_params, only: [:create]
  #before_action :configure_account_update_params, only: [:update]


  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # private

  # def sign_up_params
  #   params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  # end

  # def account_update_params
  #   params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @booked_vacuums = current_user.booked_vacuums
    @bookings = current_user.bookings
  end

  def virds
    @vacuums = current_user.owned_vacuums
  end
end

app/views/users/dashboard.html.erb
<div class="wrapper" style="background-color: #f4f4f4;">
  <div class="container">


    <div class="title">
      <h2 style="margin-top: 0;">My Booked Virds</h1>
        <h3> You have booked <%= @bookings.count %> Virds so far.. </h2>
          <div class="book-button">
            <%= link_to "Book a Vird", vacuums_path, class: "btn btn-warning btn-sm" %>
            </div>
          </div>
          <% @bookings.each do |booking| %>
          <div class="vacuum-card">
            <div class="meta">
              <div class="photo" style="background-image: url(<%= image_path (booking.vacuum.image) %>)">
              </div>
              <ul class="details">
                <li class="owner"><a href="#"><%= booking.vacuum.user.first_name %></a></li>
                <li class="date">Booked at: <%= booking.created_at.strftime("%A, %b %d") %> </li>
              </ul>
            </div>
            <div class="description">
              <h1><%= booking.vacuum.model %></h1>
              <% if booking.vacuum.available %>
              <div class="available">Available</div>
              <% else %>
              <% end %>
              <h2>this Vird costs <%= booking.vacuum.price %>$ a day </h2>
              <p> You Booked this Vird on <%= booking.created_at.strftime("%A, %b %d") %>, for <%= booking.rent_duration %> hours from this Awesome Virder: <%= booking.vacuum.user.first_name %> <br> You can book it again from the main page </p>
        <!-- <p class="read-more">
          <a href="#">More Details</a>
        </p> -->
      </div>
    </div>
    <% end %>

  </div>


<!--   <div class="vacuum-card alt">
    <div class="meta">
      <div class="photo" style="background-image: url(https://storage.googleapis.com/chydlx/codepen/blog-cards/image-2.jpg)"></div>
      <ul class="details">
        <li class="owner"><a href="#">Jane Doe</a></li>
        <li class="date">July. 15, 2015</li>
      </ul>
    </div>
    <div class="description">
      <h1>Mastering the Language</h1>
      <h2>Java is not the same as JavaScript</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad eum dolorum architecto obcaecati enim dicta praesentium, quam nobis! Neque ad aliquam facilis numquam. Veritatis, sit.</p>
      <p class="read-more">
        <a href="#">Read More</a>
      </p>
    </div>
  </div> -->

app/views/users/virds.html.erb
<h1 style="font-weight: bold; text-align: center">My Virds</h1>

<div class="container">
  <% @vacuums.each do |vacuum| %>
    <div class="list-card">
        <div>
          <%= image_tag (vacuum.image), class: 'list-image' %>
        </div>
        <div>
          <div class="list-model"><%= vacuum.model.capitalize %></div>
          <div class="list-price">$<%= vacuum.price %>/hour</div>
        </div>
        <div>
          <%= link_to "Edit", edit_vacuum_path(vacuum), class: "btn btn-default" %>
          <%= link_to "Delete", vacuum_path(vacuum), method: :delete, class: "btn btn-danger" %>
        </div>
    </div>
  <% end %>
</div>