config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', to: 'users#dashboard'
  get 'my-virds', to: 'users#virds'

  devise_for :users
  root to: 'pages#home'

  resources :vacuums do
    resources :bookings
  end
end

app/views/shared/_banner.html.erb
  <div class="banner" style="background-image:
  linear-gradient(-225deg, rgba(186,210,213,0.4) 0%, rgba(0,36,61,0.4) 50%), url(<%= image_path 'banner_vacuum.jpg' %>);">
    <div class="banner-content">
      <h1>VIRD</h1>
      <p>Clean it Up | Get Paid to Share Yours</p>
          <%= link_to "Book a Vird", vacuums_path, class: "btn btn-warning btn-lg" %>
<div class="arrow">

  <div class="chevron"></div>
  <div class="chevron"></div>
  <div class="chevron"></div>


</div>
    </div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">

  </div>

  <div class="footer-copyright">
    Made with <i class="fas fa-heart"></i> & <i class="fas fa-coffee"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "vird_logo_orange.png", height: 60 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "List your Vird", new_vacuum_path, class: "navbar-wagon-item navbar-wagon-link btn-medium" %>
      <%= link_to "My Bookings", dashboard_path , class: "navbar-wagon-item navbar-wagon-link" %>

      <% if current_user.owned_vacuums.any? %>
        <%= link_to "My Virds", my_virds_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "avatar.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_testimonials.html.erb
<div class="main-gallery">
  <div class="gallery-cell">
    <div class="testimonial">
        <img class="testimonial-avatar" src="https://res.cloudinary.com/druzius/image/upload/v1542811914/woman.jpg">
      <q class="testimonial-quote">Whenever my cleaner is coming over for his weekly session, I make sure I booked a Vird for that day.</q>
      <span class="testimonial-author">Jenny Smith, Dolphin Trainer</span>
    </div>
  </div>
  <div class="gallery-cell">
     <div class="testimonial">
        <img class="testimonial-avatar" src="https://res.cloudinary.com/druzius/image/upload/v1542811914/hipster.jpg">
      <q class="testimonial-quote">I am too lazy to buy an actual vacuum cleaner, so when my appartement gets really dirty, I just turn on the app and get a Vird</q>
      <span class="testimonial-author">Buddy Jones, Freelance Web Developer</span>
    </div>
  </div>
  <div class="gallery-cell">
        <div class="testimonial">
        <img class="testimonial-avatar" src="https://res.cloudinary.com/druzius/image/upload/v1542811914/grandmother.jpg">
      <q class="testimonial-quote">After I rented the Annihilator once, I am asking my grand children to make a mess when they come visit, so I can rent it again!</q>
      <span class="testimonial-author">Sara Waltz, Grandmother of 8</span>
    </div>
  </div>
</div>